<?php
// Database Configuration Step
$error = '';
$success = '';

if ($_POST) {
    $dbHost = $_POST['db_host'] ?? '';
    $dbName = $_POST['db_name'] ?? '';
    $dbUser = $_POST['db_user'] ?? '';
    $dbPass = $_POST['db_pass'] ?? '';
    $appUrl = $_POST['app_url'] ?? '';
    
    if (empty($dbHost) || empty($dbName) || empty($dbUser) || empty($appUrl)) {
        $error = 'Bitte fülle alle Pflichtfelder aus!';
    } else {
        try {
            // Test database connection
            $dsn = "mysql:host={$dbHost};charset=utf8mb4";
            $testConnection = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);
            
            // Create config.php
            $configContent = "<?php\n";
            $configContent .= "// RapMarket.de Configuration\n";
            $configContent .= "// Auto-generated by setup on " . date('Y-m-d H:i:s') . "\n\n";
            $configContent .= "// Datenbank Konfiguration\n";
            $configContent .= "define('DB_HOST', '{$dbHost}');\n";
            $configContent .= "define('DB_NAME', '{$dbName}');\n";
            $configContent .= "define('DB_USER', '{$dbUser}');\n";
            $configContent .= "define('DB_PASS', '{$dbPass}');\n";
            $configContent .= "define('DB_CHARSET', 'utf8mb4');\n\n";
            $configContent .= "// Anwendungs-Konfiguration\n";
            $configContent .= "define('APP_NAME', 'RapMarket.de');\n";
            $configContent .= "define('APP_URL', '{$appUrl}');\n";
            $configContent .= "define('APP_ENV', 'production');\n\n";
            $configContent .= "// Sicherheit\n";
            $configContent .= "define('JWT_SECRET', '" . bin2hex(random_bytes(32)) . "');\n";
            $configContent .= "define('PASSWORD_SALT', '" . bin2hex(random_bytes(16)) . "');\n";
            $configContent .= "define('SESSION_NAME', 'rapmarket_session');\n\n";
            $configContent .= "// E-Mail Konfiguration\n";
            $configContent .= "define('MAIL_HOST', 'smtp.gmail.com');\n";
            $configContent .= "define('MAIL_PORT', 587);\n";
            $configContent .= "define('MAIL_USERNAME', '');\n";
            $configContent .= "define('MAIL_PASSWORD', '');\n";
            $configContent .= "define('MAIL_FROM', 'noreply@rapmarket.de');\n";
            $configContent .= "define('MAIL_FROM_NAME', 'RapMarket.de');\n\n";
            $configContent .= "// API Konfiguration\n";
            $configContent .= "define('API_RATE_LIMIT', 100);\n";
            $configContent .= "define('MAX_LOGIN_ATTEMPTS', 5);\n\n";
            $configContent .= "// Punkte System\n";
            $configContent .= "define('STARTING_POINTS', 1000);\n";
            $configContent .= "define('DAILY_BONUS_POINTS', 50);\n";
            $configContent .= "define('MIN_BET_AMOUNT', 10);\n";
            $configContent .= "define('MAX_BET_AMOUNT', 1000);\n\n";
            $configContent .= "// Debug und Logging\n";
            $configContent .= "define('ENABLE_DEBUG', false);\n";
            $configContent .= "define('LOG_LEVEL', 'ERROR');\n";
            $configContent .= "define('LOG_FILE', 'logs/app.log');\n\n";
            $configContent .= "// Zeitzone\n";
            $configContent .= "date_default_timezone_set('Europe/Berlin');\n\n";
            $configContent .= "// Error Reporting\n";
            $configContent .= "error_reporting(0);\n";
            $configContent .= "ini_set('display_errors', 0);\n";
            $configContent .= "?>";
            
            if (file_put_contents('../config.php', $configContent) === false) {
                throw new Exception('Konnte config.php nicht erstellen. Prüfe die Schreibrechte!');
            }
            
            // Test the configuration by including it and creating database
            require_once '../config.php';
            
            // Check if functions exist before including
            if (!function_exists('writeLog')) {
                // Define writeLog function for setup
                function writeLog($level, $message, $context = []) {
                    error_log("[$level] $message");
                }
            }
            
            require_once '../includes/database.php';
            
            // This will automatically create the database and tables
            $db = Database::getInstance();
            
            $success = 'Datenbank-Konfiguration erfolgreich! Datenbank und Tabellen wurden automatisch erstellt.';
            
            // Store setup data in session for next step
            session_start();
            $_SESSION['setup_db_configured'] = true;
            
        } catch (Exception $e) {
            $error = 'Datenbankfehler: ' . $e->getMessage();
            // Delete config.php if created but failed
            if (file_exists('../config.php')) {
                unlink('../config.php');
            }
        }
    }
}
?>

<h3><i class="fas fa-database me-2"></i>Datenbank-Konfiguration</h3>
<p>Gib deine MySQL-Datenbank-Zugangsdaten ein:</p>

<?php if ($error): ?>
    <div class="alert alert-danger">
        <i class="fas fa-exclamation-circle me-2"></i><?= htmlspecialchars($error) ?>
    </div>
<?php endif; ?>

<?php if ($success): ?>
    <div class="alert alert-success">
        <i class="fas fa-check-circle me-2"></i><?= htmlspecialchars($success) ?>
    </div>
    <div class="text-center mt-4">
        <a href="?step=admin" class="btn btn-primary btn-lg">
            <i class="fas fa-arrow-right me-2"></i>Weiter zum Admin-Account
        </a>
    </div>
<?php else: ?>

<form method="POST" class="mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label for="db_host" class="form-label">
                    <i class="fas fa-server me-1"></i>Datenbank Host *
                </label>
                <input type="text" class="form-control" id="db_host" name="db_host" 
                       value="<?= $_POST['db_host'] ?? 'localhost' ?>" required>
                <small class="form-text text-muted">Meist 'localhost' oder IP-Adresse</small>
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="db_name" class="form-label">
                    <i class="fas fa-database me-1"></i>Datenbank Name *
                </label>
                <input type="text" class="form-control" id="db_name" name="db_name" 
                       value="<?= $_POST['db_name'] ?? 'rapmarket' ?>" required>
                <small class="form-text text-muted">Wird automatisch erstellt falls nicht vorhanden</small>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                <label for="db_user" class="form-label">
                    <i class="fas fa-user me-1"></i>Datenbank Benutzername *
                </label>
                <input type="text" class="form-control" id="db_user" name="db_user" 
                       value="<?= $_POST['db_user'] ?? '' ?>" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="mb-3">
                <label for="db_pass" class="form-label">
                    <i class="fas fa-lock me-1"></i>Datenbank Passwort
                </label>
                <input type="password" class="form-control" id="db_pass" name="db_pass" 
                       value="<?= $_POST['db_pass'] ?? '' ?>">
                <small class="form-text text-muted">Leer lassen falls kein Passwort</small>
            </div>
        </div>
    </div>
    
    <div class="mb-3">
        <label for="app_url" class="form-label">
            <i class="fas fa-link me-1"></i>Website URL *
        </label>
        <input type="url" class="form-control" id="app_url" name="app_url" 
               value="<?= $_POST['app_url'] ?? 'http://localhost/rapmarket' ?>" required>
        <small class="form-text text-muted">Die vollständige URL zu deiner RapMarket Installation</small>
    </div>
    
    <div class="alert alert-info">
        <i class="fas fa-info-circle me-2"></i>
        <strong>Automatische Installation:</strong><br>
        Die Datenbank und alle Tabellen werden automatisch erstellt. Du musst nichts manuell importieren!
    </div>
    
    <div class="d-flex justify-content-between">
        <a href="?step=welcome" class="btn btn-outline-secondary">
            <i class="fas fa-arrow-left me-2"></i>Zurück
        </a>
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-check me-2"></i>Datenbank konfigurieren
        </button>
    </div>
</form>

<?php endif; ?>